"""Conservative, hand-reviewed FACT entries for data/facts.json.

These avoid uncertain viral trivia and specialist claims. Notes are optional
and never introduce a second unsupported biological claim.
"""

FACTS = [
    # Social behavior and communication (1-50)
    ("Cats have flexible social lives: some live alone, while others form stable groups.", "The answer is not ‘aloof.’ The answer is ‘it depends.’"),
    ("Free-ranging cat groups often center on related females and their kittens.", "The neighborhood committee has whiskers."),
    ("Food availability helps determine how closely free-ranging cats live together.", "Resources first. Friendship negotiations later."),
    ("Cats use distance, posture, scent, and sound to manage social encounters.", "A complete communications department, mostly ignored by humans."),
    ("Friendly cats may greet by touching noses.", "A tiny diplomatic summit."),
    ("Cats may groom familiar companions as a social behavior.", "Mutual hair maintenance means the alliance holds."),
    ("Rubbing can be both an affectionate interaction and a way to deposit scent.", "You have been greeted and labeled."),
    ("Cats have scent glands around the cheeks and other parts of the body.", "The face is also a rubber stamp."),
    ("Scratching leaves both a visible mark and scent from the paws.", "The memo is vertical and legally binding."),
    ("Urine spraying is a marking behavior, not the same posture as ordinary urination.", "Different paperwork. Same terrible department."),
    ("The flehmen response helps cats investigate chemical signals with the vomeronasal organ.", "That open-mouth face is serious laboratory work."),
    ("An upright tail often appears in friendly feline greetings.", "A small flag of diplomatic intent."),
    ("A puffed tail signals strong arousal, which may include fear or excitement.", "The bottle brush has entered the chat."),
    ("Flattened ears can signal fear, stress, or defensive aggression.", "The radar dishes have filed an objection."),
    ("Dilated pupils can reflect dim light or emotional arousal.", "Context matters. The eyes refuse to explain further."),
    ("A slow blink can function as a relaxed, non-threatening signal.", "The smallest possible peace treaty."),
    ("A hiss is usually a defensive warning asking for more distance.", "The boundary has subtitles."),
    ("Growling is a warning sound that can precede stronger defensive behavior.", "Customer service is now closed."),
    ("Purring is not limited to happiness; cats may also purr when stressed or unwell.", "The motor has more than one setting."),
    ("Adult cats use meows especially often when communicating with humans.", "We received a custom notification system."),
    ("Kittens mew to attract their mother’s attention.", "The original support ticket."),
    ("Trills and chirps commonly appear in greetings or attention-seeking.", "A polite little modem connecting."),
    ("Cat body language works as a whole: ears, eyes, whiskers, tail, and posture all matter.", "Never diagnose the meeting from one tail twitch."),
    ("An exposed belly can show trust without being an invitation to touch it.", "The exhibit is open. The gift shop is not."),
    ("Kneading begins as a nursing behavior in kittens and often continues in adults.", "The bakery survives long after weaning."),
    ("Cats can form strong attachments to people and familiar animals.", "Aloofness allegations remain unproven."),
    ("Cats can recognize familiar human voices.", "Recognition and compliance are separate subscriptions."),
    ("Research shows cats can learn the sound pattern of their own names.", "Whether they attend the meeting is another matter."),
    ("Cats learn through consequences and can be trained with rewards.", "The intern accepts payment in chicken."),
    ("A clicker can mark the exact moment a cat performs a wanted behavior.", "Tiny sound. Immediate invoice."),
    ("Punishment can increase fear and damage a cat’s relationship with people.", "Management by intimidation has failed again."),
    ("Predictable routines can help cats feel secure.", "Breakfast at 07:00 remains constitutional law."),
    ("Hiding gives cats a way to gain distance and control when they feel unsure.", "The bunker is a coping strategy, not a personal insult."),
    ("Elevated perches can provide cats with exploration and a sense of safety.", "The cabinet is now an observation deck."),
    ("Cats need opportunities to scratch; it is a normal behavior, not revenge.", "The sofa was never the target personally."),
    ("Cats may prefer different scratching materials, angles, and locations.", "Every contractor has specifications."),
    ("Many cats dig before or after eliminating, but not every cat buries waste.", "Some file the report. Some leave it on the desk."),
    ("Cats can develop preferences for particular litter textures and box locations.", "Facilities management is a delicate negotiation."),
    ("Most cats prefer clean litter boxes with easy access.", "The restroom complaint is usually actionable."),
    ("Food, water, litter, resting, and scratching resources can be separated to reduce conflict.", "Open-plan offices were a mistake."),
    ("Cats can live socially, but forced closeness may create tension.", "Roommates require an exit strategy."),
    ("Related female cats may cooperate while raising kittens.", "The nursery has a rotating staff."),
    ("Cat play often contains pieces of the hunting sequence: stalk, chase, pounce, and bite.", "The ribbon has become legally prey."),
    ("Well-fed cats may still hunt because predatory behavior is not controlled by hunger alone.", "Dinner does not cancel the side quest."),
    ("Moving toys can trigger stalking and pouncing more effectively than motionless ones.", "The prey must respect production values."),
    ("Short, repeated play sessions can fit a cat’s natural activity pattern.", "Several tiny appointments with chaos."),
    ("Puzzle feeders can combine food with exploration and problem-solving.", "Lunch now requires credentials."),
    ("Individual cats differ widely in play, touch, food, and social preferences.", "The species has no universal settings menu."),
    ("A cat may chatter while watching prey, but the exact reason remains uncertain.", "Science has logged the noise and no explanation."),
    ("Cats can adjust their activity schedule around household routines.", "The dawn shift is negotiable. Barely."),

    # Senses, anatomy, and movement (51-100)
    ("Domestic cats are obligate carnivores with nutritional needs tied to animal tissue.", "The salad position remains ceremonial."),
    ("Adult cats normally have 30 permanent teeth.", "Thirty tiny reasons not to hand-feed carelessly."),
    ("Kittens normally develop 26 deciduous, or baby, teeth.", "The starter set is also extremely pointy."),
    ("Cats grow two sets of teeth: deciduous teeth and permanent teeth.", "One mouth, two hardware releases."),
    ("Carnassial teeth act like shears for cutting food.", "The mouth contains dedicated scissors."),
    ("A cat’s jaw is built mainly for strong up-and-down biting rather than broad side-to-side grinding.", "The chewing interface is extremely specialized."),
    ("Backward-facing keratin papillae give a cat’s tongue its rough surface.", "The washcloth has hooks."),
    ("Tongue papillae help cats groom and remove material from food.", "One tool, several alarming departments."),
    ("Cats walk on their toes, a posture called digitigrade locomotion.", "Permanent tiptoe mode."),
    ("Most cats have five digits on each front paw and four on each hind paw.", "Standard issue; exceptions arrive with bonus beans."),
    ("The inner front digit is commonly called the dewclaw.", "A spare hook mounted above the main crew."),
    ("Polydactyl cats are born with extra digits.", "The bean budget has been exceeded."),
    ("Most domestic cats can retract their claws when the claws are not in use.", "The knives come with storage."),
    ("Claws grow in layers, and cats shed old outer claw sheaths.", "Finding a hollow claw is normal hardware maintenance."),
    ("Scratching helps remove worn outer claw sheaths.", "The manicure is structural."),
    ("Paw pads cushion the feet and help cats move quietly.", "Noise reduction installed at the factory."),
    ("Cats have sweat glands in their paw pads.", "Nervous toe beans may leave tiny damp prints."),
    ("Whiskers are specialized touch hairs called vibrissae.", "Facial antennae, officially."),
    ("Whisker follicles are richly supplied with nerves.", "Each antenna has premium wiring."),
    ("Cats have whiskers above the eyes as well as around the muzzle.", "The eyebrow department also runs sensors."),
    ("Cats also have sensory hairs on the backs of their front legs.", "The forelegs quietly joined the radar network."),
    ("Whiskers help detect nearby objects and air movement.", "Close-range navigation remains operational in the dark."),
    ("Cutting whiskers removes useful sensory input until they regrow.", "Do not uninstall the proximity sensors."),
    ("A cat’s whiskers do not guarantee that every opening fits the rest of the body.", "The whisker-width rule has exceptions and confidence issues."),
    ("Cats have a third eyelid, also called the nictitating membrane.", "A backup curtain lives in the corner."),
    ("The tapetum lucidum reflects light inside a cat’s eye.", "This is why headlights activate the tiny mirrors."),
    ("Cats see better than humans in dim light, but they cannot see in complete darkness.", "Night vision still requires some night."),
    ("Domestic cats usually have vertical slit-shaped pupils.", "The aperture is built for dramatic close-ups."),
    ("Cats distinguish some colors, though their color vision differs from human vision.", "The world is not grayscale; it is merely differently graded."),
    ("A cat can move each external ear independently.", "Two radar dishes, separate management."),
    ("The external ear funnels sound toward the ear canal.", "The satellite dish is biological."),
    ("Cats can hear frequencies above the upper range of human hearing.", "Some meetings occur entirely outside our clearance."),
    ("A cat’s inner-ear vestibular system helps control balance and coordinate head and eye movement.", "The onboard gyroscope is doing paperwork."),
    ("The righting reflex helps a falling cat orient its feet toward the ground.", "A reflex, not a supernatural guarantee."),
    ("The righting reflex needs time to work and cannot make every fall safe.", "Physics keeps veto power."),
    ("A cat’s flexible spine contributes to long strides and rapid body rotation.", "The chassis bends where ours files complaints."),
    ("A cat’s shoulder blades are attached largely by muscles rather than a rigid bony joint.", "The front suspension is unusually mobile."),
    ("A cat’s small clavicles do not anchor the shoulders like human collarbones do.", "The shoulder assembly declined the fixed contract."),
    ("Strong hind limbs provide much of a cat’s jumping power.", "The rear launch system is fully armed."),
    ("The tail can help with balance and rapid turns.", "The counterweight is also expressive."),
    ("Tailless cats can still balance by using the rest of the body and vestibular system.", "The backup systems remain excellent."),
    ("Cats use smell to gather social and environmental information.", "The room contains an invisible bulletin board."),
    ("The vomeronasal organ helps cats analyze certain chemical signals.", "A second smell office handles confidential mail."),
    ("Cats have limited ability to taste sweetness because a sweet-receptor gene is nonfunctional.", "Dessert was removed from the firmware."),
    ("Smell strongly influences a cat’s interest in food.", "Dinner must pass inspection before tasting begins."),
    ("A wet or dry nose by itself does not reliably measure a cat’s health.", "The nose is not a diagnostic dashboard."),
    ("Cats lap liquid by rapidly lifting a column of fluid with the tongue.", "Drinking is a high-speed physics demonstration."),
    ("Cats groom with the tongue, teeth, and front paws.", "The cleaning crew carries no equipment bag."),
    ("Grooming removes loose hair and debris from the coat.", "Routine maintenance generates its own hairball paperwork."),
    ("Saliva evaporating from groomed fur can contribute to cooling.", "Air conditioning, applied one lick at a time."),

    # Kittens, coats, domestication, and daily life (101-150)
    ("Domestic cats belong to the species Felis catus.", "A formal name for the animal on the keyboard."),
    ("Domestic cats belong to the family Felidae with wild cats such as lions and lynxes.", "The family resemblance occasionally attacks a shoelace."),
    ("The main wild ancestor of domestic cats is the African and Southwest Asian wildcat, Felis silvestris lybica.", "The ancient face remains remarkably familiar."),
    ("Cat domestication began around early farming communities in the Fertile Crescent.", "Stored grain attracted rodents; rodents attracted management."),
    ("Cats later gained major cultural and religious importance in ancient Egypt.", "The promotion to divine-adjacent was substantial."),
    ("Ancient DNA indicates cats spread along human trade and travel routes.", "The distribution network had paws."),
    ("Sailors carried cats aboard ships, where hunting rodents protected stored food.", "Maritime pest control required naps."),
    ("Domestic cats retain many physical features and behaviors of their wildcat ancestors.", "The wilderness still fits under the sofa."),
    ("A human buried with a cat in Cyprus provides early evidence of a close relationship thousands of years ago.", "Someone wanted the friendship recorded permanently."),
    ("The tabby is a coat pattern, not a breed.", "The forehead M carries no membership card."),
    ("Common tabby patterns include mackerel, classic, spotted, and ticked.", "Striped management offers several uniforms."),
    ("The familiar M-shaped forehead marking appears in many tabby coats.", "No, it does not stand for management. Probably."),
    ("Orange coat color is linked to a gene on the X chromosome.", "Genetics selected the high-visibility uniform."),
    ("Most tortoiseshell cats are female because orange and non-orange coat genes are X-linked.", "The patchwork follows chromosome logistics."),
    ("Male tortoiseshell and calico cats are uncommon, but they do exist.", "Genetics permits rare limited editions."),
    ("A calico coat combines orange and dark patches with white spotting.", "Three-color paperwork, one cat."),
    ("In cat coat terminology, blue is a dilute form of black.", "The color department named gray after the drama."),
    ("Cream is a dilute form of orange in cat coat genetics.", "Orange, with the volume turned down."),
    ("A solid white coat is not the same genetic condition as albinism.", "White has more than one route through the code."),
    ("Heterochromia means the two eyes have different colors.", "The face selected mismatched windows."),
    ("Colorpoint coats darken more on cooler parts of the body.", "The ears, face, feet, and tail receive the dramatic shading."),
    ("Colorpoint kittens are born pale because the womb is warm.", "The paint develops after delivery."),
    ("Many hairless cats still have a fine layer of down rather than completely bare skin.", "The peach-fuzz setting is active."),
    ("Hairless cats still produce skin oils that fur would normally help distribute.", "No fur does not mean no maintenance."),
    ("Long hair in domestic cats is commonly associated with recessive gene variants.", "The fluff may hide for a generation."),
    ("Polydactyly is inherited in some cat family lines.", "Bonus beans can run in the family."),
    ("Coat color alone does not reliably determine a cat’s personality.", "Orange allegations remain anecdotal."),
    ("Kittens are born with their eyes closed.", "The launch begins in safe mode."),
    ("Newborn kittens are also born with closed ear canals.", "Audio support arrives shortly after launch."),
    ("Newborn kittens rely on their mother for warmth because temperature control is still developing.", "The heating system is maternal."),
    ("Mother cats lick newborn kittens to stimulate urination and defecation.", "Early technical support is extremely hands-on."),
    ("A kitten’s eyes usually begin opening during the second week of life.", "The curtains rise gradually."),
    ("Kittens begin standing and walking before their coordination is fully convincing.", "Version one locomotion is mostly wobble."),
    ("Baby teeth begin appearing while kittens are still only a few weeks old.", "The tiny needles arrive early."),
    ("Permanent teeth replace kitten teeth over the first several months of life.", "The hardware upgrade completes surprisingly fast."),
    ("Weaning is a gradual transition from milk to solid food.", "Lunch changes departments over several weeks."),
    ("Play with littermates helps kittens practice social and hunting behaviors.", "The nursery doubles as combat school."),
    ("Early positive experiences with people can shape a kitten’s later comfort around humans.", "First impressions have long tails."),
    ("Cats are induced ovulators: mating triggers the release of eggs.", "Reproductive scheduling waits for an event notification."),
    ("Cat pregnancy typically lasts about nine weeks.", "A full litter ships on a brisk schedule."),
    ("Kittens in one litter can have different fathers.", "The family tree may require several branches."),
    ("Many kittens begin with blue-looking eyes that change as pigment develops.", "The default theme may not be permanent."),
    ("A cat’s adult personality reflects both inherited tendencies and life experience.", "Nature and nurture share the admin password."),
    ("A stray cat has lived with people, while a feral cat may have had little human socialization.", "The labels describe history, not moral character."),
    ("Indoor cats still need climbing, scratching, hiding, play, and exploration.", "A roof does not cancel the cat software."),
    ("Older cats may sleep more and become less active than younger adults.", "Senior management delegates the zoomies."),
    ("Hearing and vision can change as cats age.", "The sensors also accumulate birthdays."),
    ("Arthritis can make high-sided litter boxes and tall jumps harder for older cats.", "Accessibility applies to tiny bathrooms too."),
    ("A cat’s grooming may become less thorough with age or reduced mobility.", "Maintenance gets harder when the hinges complain."),
    ("Regular gentle handling can help people notice changes in a cat’s skin, coat, or body.", "Routine inspection, with consent and snacks."),

    # Feeding, rest, enrichment, and practical biology (151-200)
    ("Cats require dietary taurine because they cannot make enough for their needs.", "The nutrient must arrive with dinner."),
    ("Cats need preformed vitamin A in their diet rather than relying only on plant carotenoids.", "The carnivore firmware expects the finished ingredient."),
    ("Cats have a dietary requirement for arachidonic acid, an animal-derived fatty acid.", "Another line item on the obligate-carnivore invoice."),
    ("A nutritionally complete cat food is formulated differently for kittens and adults.", "Growth mode and maintenance mode use different specifications."),
    ("Many adult cats digest lactose poorly after weaning.", "The saucer of milk has been removed from the official plan."),
    ("Cats do not need cow’s milk as part of a balanced diet.", "The cartoon contract was never signed."),
    ("Cats obtain water from both food and drinking.", "Hydration has two delivery routes."),
    ("Wet cat food contains more water than dry cat food.", "The clue is unusually present in the name."),
    ("Smell can affect whether a cat accepts or rejects food.", "Dinner faces a nose-led review board."),
    ("Cats often prefer food and water placed away from the litter area.", "Kitchen and bathroom remain separate departments."),
    ("Fresh, clean water should remain available even when a cat eats wet food.", "The beverage station stays open."),
    ("Cats can prefer different bowl shapes, water locations, or moving water.", "Hydration comes with user-interface testing."),
    ("Eating many small portions matches the pattern created by catching small prey.", "The tasting menu predates restaurants."),
    ("Food puzzles can slow eating while adding exploration and manipulation.", "The meal now has a security puzzle."),
    ("Cats use their rough tongues to help pull food from surfaces.", "The built-in scraper reports for duty."),
    ("A cat’s appetite may drop when smell is reduced.", "If dinner loses its scent, the review collapses."),
    ("Cats alternate between sleep, light dozing, and periods of alert rest.", "Several levels of unavailable."),
    ("Cats experience REM sleep, the sleep stage associated with dreaming in humans.", "The paws may be attending a private chase."),
    ("Small twitches can occur while a cat is asleep.", "The dream has minor special effects."),
    ("Cats are often most active around dawn and dusk, a pattern called crepuscular activity.", "The schedule was designed before alarm clocks."),
    ("Cats are not strictly nocturnal and can adapt activity to their environment.", "Night shift is common, not mandatory."),
    ("Rest conserves energy between short bursts of hunting, play, or exploration.", "The loaf is charging."),
    ("A box can provide a cat with cover, warmth, and a defined boundary.", "Three benefits, four cardboard walls."),
    ("Studies in shelters have found that access to hiding boxes can reduce stress for some cats.", "Cardboard earns a peer-reviewed promotion."),
    ("A secure hiding place gives a cat control over when to approach.", "The meeting begins when the bunker says so."),
    ("Cats may choose warm resting places because their thermoneutral range is warmer than ours.", "The sunbeam is an environmental setting."),
    ("Cats change sleeping positions to conserve or release body heat.", "Tight cinnamon roll in winter; long noodle when warm."),
    ("A curled sleeping posture reduces exposed surface area.", "The heat budget has entered compact mode."),
    ("A stretched sleeping posture exposes more body surface to the air.", "The radiator has become a cooling rack."),
    ("Cats may rotate preferred sleeping spots as temperature, light, and household activity change.", "The nap map updates without notice."),
    ("Sunbathing can warm a cat without extra metabolic effort.", "Solar-powered loafing is efficient."),
    ("Play behavior can continue throughout a cat’s life.", "Adulthood does not revoke spring privileges."),
    ("Older cats may prefer gentler, shorter play sessions.", "The hunt remains; the calendar has opinions."),
    ("Toy movement away from a cat can resemble fleeing prey.", "The ribbon understands stage direction."),
    ("Letting a cat catch a toy can complete the play sequence.", "The hunter requires a successful quarterly result."),
    ("Hands used as toys can teach kittens that human skin is a biting target.", "The hand should not join the prey department."),
    ("Scratching posts work best when they are stable enough not to wobble.", "Infrastructure matters to the contractor."),
    ("Placing a scratcher near a sleeping area can suit the stretch-and-scratch routine.", "Wake, extend, file paperwork."),
    ("Some cats prefer vertical scratchers while others prefer horizontal surfaces.", "Orientation is a personal specification."),
    ("Cats may scratch after waking as part of stretching and scent marking.", "Morning correspondence begins immediately."),
    ("A cat’s claws are used for climbing, gripping, defense, and prey handling.", "A compact multipurpose toolset."),
    ("Cats can climb upward more easily than they climb down headfirst.", "The hooks were designed for ascent."),
    ("Many cats descend trees backward so the claws can maintain their grip.", "Reverse gear solves the claw geometry."),
    ("A cat can jump without a running start by rapidly extending the hind legs.", "The launch sequence fits on one floor tile."),
    ("Cats use the forelegs to absorb and control a landing.", "Front suspension handles the arrival paperwork."),
    ("Balance depends on vision, inner-ear signals, touch, muscles, and body position working together.", "No single sensor gets sole credit for the shelf."),
    ("Cats can learn routes and remember where important resources are located.", "The house map highlights food and forbidden cabinets."),
    ("Cats investigate new objects using sight, smell, whiskers, and cautious touch.", "The inspection team approaches sideways."),
    ("Novel scents, objects, or sounds can be enriching when introduced without forcing contact.", "Curiosity needs an exit door."),
    ("A cat’s preferences can change with age, health, experience, and environment.", "Settings may update without patch notes."),
]


MYTHS = [
    ("Cats always land on their feet.", "The righting reflex needs time and cannot make every fall safe."),
    ("A high fall cannot hurt a cat.", "Cats can suffer severe or fatal injuries from falls at any height."),
    ("Cats have nine lives.", "Excellent reflexes are still only one life with unusually good suspension."),
    ("Cats can see in complete darkness.", "Their low-light vision is excellent, but it still requires some light."),
    ("Whiskers perfectly measure every gap a cat can fit through.", "Whiskers provide nearby sensory information; body width and fluff still vary."),
    ("Cutting whiskers is harmless grooming.", "It removes important sensory input until the whiskers regrow."),
    ("Whiskers are the only reason cats can balance.", "Balance combines inner-ear, visual, touch, muscle, and body-position information."),
    ("A purring cat is always happy.", "Cats may also purr while stressed, frightened, in pain, or unwell."),
    ("Cats are naturally cold and incapable of affection.", "Cats form attachments and show affection in individual, sometimes subtle ways."),
    ("Cats cannot be trained.", "Reward-based training can teach cues, tricks, handling, and useful routines."),
    ("A cat eliminates outside the box purely out of spite.", "Medical, environmental, litter, access, or stress problems are far more useful explanations."),
    ("Every hiss means a cat is about to attack.", "A hiss usually warns that the cat wants distance and hopes to avoid escalation."),
    ("A displayed belly is permission for a belly rub.", "It can signal trust while the vulnerable abdomen remains strictly off-limits."),
    ("A twitching cat tail means the same thing as a wagging dog tail.", "Feline tail movement often signals arousal or irritation; context decides the rest."),
    ("Cats are completely solitary and never form friendships.", "Cats have flexible social systems and can form stable bonds."),
    ("Adult cats constantly meow to communicate with other adult cats.", "Adult meowing is used especially often in cat-human communication."),
    ("Kneading proves an adult cat is hungry.", "It begins during nursing but can continue during comfort, settling, or affection."),
    ("Rubbing against a person means only ‘pet me.’", "Rubbing can combine greeting, contact, and scent deposition."),
    ("Furniture scratching is calculated revenge.", "Scratching is normal claw care, stretching, and visual-scent marking."),
    ("Declawing is just a permanent nail trim.", "It removes the end of each toe, not merely the claw."),
    ("Cats do not recognize their names.", "Studies show cats can distinguish the sound pattern of their own names."),
    ("Cats and dogs can never become companions.", "Careful introductions and compatible individuals can produce strong cross-species bonds."),
    ("Black cats bring bad luck.", "Coat pigment has no supernatural control over your calendar."),
    ("Coat color reliably predicts personality.", "Personality depends on genetics, development, experience, health, and environment—not one color."),
    ("Every orange cat is male.", "Orange is sex-linked, so males are common, but orange females absolutely exist."),
    ("Calico is a cat breed.", "Calico describes a coat color pattern found across multiple breeds and mixed-breed cats."),
    ("Tabby is a cat breed.", "Tabby describes patterns such as mackerel, classic, spotted, and ticked."),
    ("Every solid-white cat is deaf.", "Deafness risk is higher in some white cats, but many hear normally."),
    ("Blue-eyed cats are always blind.", "Eye color does not automatically determine vision."),
    ("Hairless cats cannot trigger allergies.", "Allergens come from saliva and skin secretions too, not only loose fur."),
    ("Hairless cats require no grooming.", "Skin oils still accumulate and routine care remains necessary."),
    ("Long-haired cats always shed more than short-haired cats.", "Shedding varies by individual coat, season, health, and grooming."),
    ("Indoor cats need no enrichment.", "Indoor cats still need climbing, hiding, scratching, play, and exploration."),
    ("Indoor cats never need veterinary care.", "Indoor life reduces some risks, not illness, injury, dental disease, or aging."),
    ("Cow’s milk is the perfect everyday drink for cats.", "Many adults digest lactose poorly, and balanced food plus water meets their needs."),
    ("Cats need cow’s milk to stay healthy.", "After weaning, cats need fresh water and complete nutrition—not a cartoon saucer."),
    ("A fish-only diet is complete nutrition for cats.", "Cats require a balanced range of nutrients that one ingredient cannot reliably provide."),
    ("Raw meat is automatically safer and healthier than complete cat food.", "Raw diets can be nutritionally unbalanced and carry pathogens."),
    ("Dog food is suitable as a cat’s long-term diet.", "Cats have species-specific nutrient needs that dog food may not meet."),
    ("Cats can thrive on an improvised vegetarian diet.", "They are obligate carnivores with nutrients that must be supplied in feline-appropriate form."),
    ("Crunchy food automatically cleans every cat’s teeth.", "Ordinary kibble is not a substitute for dental assessment or appropriate dental care."),
    ("Wet food inevitably ruins a cat’s teeth.", "Dental disease has many causes; moisture content alone does not decide it."),
    ("Every cat safely stops eating when full.", "Appetite and feeding behavior vary; some cats overeat when food is unlimited."),
    ("A fat cat is automatically a happy, healthy cat.", "Excess body weight can reduce mobility and increase health risks."),
    ("Frequent hairballs are always harmless and normal.", "Repeated vomiting or hairballs deserve veterinary discussion, especially if the pattern changes."),
    ("Regular vomiting is simply what cats do.", "Vomiting can have many causes and repeated episodes are not a personality trait."),
    ("A warm, dry nose proves a cat has a fever.", "Nose moisture and temperature vary; they are not reliable stand-alone diagnostics."),
    ("Garlic is a natural dewormer for cats.", "Garlic can be toxic to cats and is not a safe parasite treatment."),
    ("Pregnant cats should be given bowls of cow’s milk.", "Pregnancy calls for appropriate complete nutrition and veterinary guidance, not mandatory dairy."),
    ("Kittens can eat any adult cat food and grow normally.", "Growing kittens need food formulated to meet growth requirements."),
    ("Cats steal a sleeping baby’s breath.", "This old superstition is not biology; safe infant sleep still means keeping pets out of the sleep space."),
    ("Pregnancy means a household must immediately give away its cat.", "Hygiene, litter precautions, and medical advice manage toxoplasmosis risk without automatic surrender."),
    ("Touching any cat automatically spreads disease.", "Risk depends on the disease and exposure; ordinary contact is not universal contagion."),
    ("Cats cannot get rabies.", "Cats are mammals and can contract rabies where the virus circulates."),
    ("An indoor cat cannot possibly get fleas.", "Fleas can enter on other animals, people, or objects."),
    ("Every pet cat needs a weekly bath.", "Most healthy cats groom themselves; bathing needs depend on coat, health, and circumstances."),
    ("All cats hate water.", "Reactions vary; some investigate, play in, or willingly enter water."),
    ("Cats are unable to swim.", "Cats can swim, though many prefer not to submit a demonstration."),
    ("A cat needs a tail in order to balance.", "The tail helps, but tailless cats balance using other body and sensory systems."),
    ("One cat year always equals seven human years.", "Cats mature quickly early on, so aging does not follow a fixed seven-to-one line."),
    ("Cats are strictly nocturnal.", "They are often crepuscular and can adjust activity to the household."),
    ("A sleeping cat is lazy.", "Rest is normal feline biology and supports short bursts of intense activity."),
    ("A hunting cat must be starving.", "Predatory behavior can occur even when nutritional needs are met."),
    ("A cat bringing prey is definitely presenting a human with a gift.", "The motive is uncertain; transport, play, safety, and hunting behavior are all possible."),
    ("Every cat responds to catnip.", "Sensitivity is inherited, and many cats show little or no response."),
    ("Catnip is dangerously addictive.", "Catnip responses are temporary and it is not considered chemically addictive."),
    ("Catnip permanently changes a cat’s personality.", "The response fades; the underlying cat returns to management."),
    ("Neutering inevitably makes a cat lazy.", "Activity and weight depend on diet, enrichment, health, age, and the individual."),
    ("A female cat needs one litter before being spayed.", "There is no health requirement to produce a litter first."),
    ("Cats must roam outdoors to have a fulfilling life.", "A well-designed indoor environment can provide safety, play, climbing, choice, and stimulation."),
    ("Older cats are too stubborn to learn anything new.", "Senior cats can learn with suitable rewards, pacing, and physical accommodations."),
    ("Two cats will settle a serious conflict if people force them together.", "Forced proximity can intensify fear and aggression; gradual introductions work better."),
    ("A squirt bottle teaches a cat which behavior is wrong.", "It may instead teach fear of the person or bottle without teaching a better choice."),
    ("A cat that hides is being rude.", "Hiding is a normal strategy for gaining safety, distance, and control."),
    ("Cats deliberately knock objects down to test human loyalty.", "They may explore movement, seek attention, hunt, or simply occupy the same surface."),
]


LORE = [
    ("Ancient Egyptians represented Bastet as a cat or a cat-headed woman.", "Divine iconography understood the assignment."),
    ("Bubastis in the Nile Delta was the principal cult center of Bastet.", "A whole city placed the cat goddess on the org chart."),
    ("Bastet became associated with protection, motherhood, joy, music, and dance.", "The portfolio was broad and impeccably feline."),
    ("The British Museum’s Gayer-Anderson Cat is a bronze Bastet figure from around 600 BCE.", "Ancient metal cat, still posing flawlessly."),
    ("Ancient Egyptian worshippers paid for ceremonial cat burials as offerings to Bastet.", "Devotion developed an extensive feline department."),
    ("Ancient Egyptian tomb paintings sometimes show cats beside their human households.", "The family portrait already had management present."),
    ("Cats were valued in ancient Egypt for controlling mice, rats, and snakes.", "Sacred-adjacent, but still on pest duty."),
    ("Mafdet was an early Egyptian feline deity linked with protection against dangerous creatures.", "Before Bastet, another cat already handled security."),
    ("Sekhmet, the Egyptian lioness goddess, embodied destructive power and protection.", "Big dramatic energy received official divine status."),
    ("Ancient Egyptian writing used forms such as ‘miw’ for cat.", "The word appears to have arrived with its own meow."),
    ("Herodotus described enormous festivals held for Bastet at Bubastis.", "The ancient travel review reports peak cat turnout."),
    ("Egyptian artisans made cat-shaped amulets in materials including faience and bronze.", "Pocket-sized divine supervision was available."),
    ("Some ancient bronze cat figures wore modeled earrings and nose rings.", "Formal portrait day demanded accessories."),
    ("Bastet’s worship continued into Egypt’s Greek and Roman periods.", "The cult survived several management changes."),
    ("A human and cat were buried together in Cyprus roughly 9,500 years ago.", "An ancient relationship left a permanent receipt."),
    ("Roman mosaics and art sometimes depict domestic cats hunting birds.", "The side quest made it into the décor."),
    ("The tomb painting of Nebamun includes a cat hunting birds in a marsh.", "Even formal art captured one extremely busy employee."),
    ("Ancient DNA shows cats traveled along Mediterranean trade routes.", "Commerce moved grain, pottery, and freeloading mousers."),
    ("Ships carried cats to protect food stores from rodents.", "The maritime job included hunting and extensive hammock testing."),
    ("Cats reached distant ports alongside merchants, sailors, and settlers.", "Global distribution was achieved without filling in customs forms."),
    ("Pangur Bán is a ninth-century Irish poem about a monk and his white cat.", "Scholar studies words; cat studies mice; both claim focus."),
    ("Medieval manuscripts preserve paw prints where cats walked across wet ink.", "The oldest known ‘sent from my keyboard’ incident."),
    ("Medieval manuscript margins contain cats fighting, hunting, playing, and behaving suspiciously.", "The doodle economy was thriving."),
    ("Exeter Cathedral has a medieval cat hole cut into a door for a resident mouser.", "Architecture eventually accepted the employee entrance."),
    ("European witch-trial lore often cast cats as witches’ familiars.", "Ordinary pet ownership received an extremely bad press cycle."),
    ("Black-cat luck traditions differ: some call them unlucky, while others welcome them.", "Superstition cannot agree on the performance review."),
    ("Ypres once held a cruel cat-throwing custom; today its festival throws toy cats instead.", "History was patched with plush."),
    ("Dick Whittington’s fortune-making cat belongs mainly to later English legend and pantomime.", "The cat handled branding while history handled paperwork."),
    ("Puss in Boots is a European folktale cat who wins status through audacious trickery.", "Footwear plus confidence defeated the class system."),
    ("In Norse mythology, the goddess Freyja rides in a chariot drawn by cats.", "Divine transport chose maximum softness and minimum compliance."),
    ("Scottish and Irish folklore describes the Cat Sìth, a large fairy cat.", "The highlands installed supernatural feline management."),
    ("Cat Sìth stories often describe a black cat with a white chest patch.", "One formal bib, several supernatural concerns."),
    ("Some Samhain folklore says leaving milk for the Cat Sìth could earn a blessing.", "The old protection fee was dairy-based."),
    ("Japan’s maneki-neko figurine raises a paw to beckon luck or customers.", "Retail strategy: wave forever, nap never."),
    ("Tokyo’s Gōtoku-ji temple is closely associated with rows of maneki-neko figures.", "The lucky-cat inventory has become architectural."),
    ("Japanese folklore calls a shape-shifting supernatural cat a bakeneko.", "The household pet has unlocked advanced permissions."),
    ("The nekomata is a Japanese cat yōkai often depicted with a forked tail.", "One tail was apparently insufficient for supernatural administration."),
    ("The kasha of Japanese folklore is a fiery catlike yōkai linked with funerals.", "A deeply unhelpful specialist arrives after dark."),
    ("One Japanese zodiac folktale says the rat tricked the cat out of attending the heavenly race.", "The calendar feud allegedly began with bad directions."),
    ("Tama became stationmaster of Kishi Station in Japan and drew visitors to the railway.", "Public transit discovered the perfect executive."),
    ("Edo-period artist Utagawa Kuniyoshi repeatedly filled prints with cats.", "One celebrated artist also maintained a serious cat folder."),
    ("Kuniyoshi arranged cats into visual puns, actors, monsters, and human activities.", "The meme format predates the modem."),
    ("Vietnam’s zodiac includes the Cat where the Chinese zodiac has the Rabbit.", "One calendar made the obvious casting change."),
    ("Chinese tradition names Li Shou as a feline protector of crops against rats.", "Agricultural security acquired divine whiskers."),
    ("Chinese art uses cat-and-butterfly imagery as a wish for long life.", "A visual wordplay sends birthday paperwork through animals."),
    ("Abu Hurairah’s famous nickname means ‘father of the kitten.’", "A companion of Muhammad entered history with elite cat branding."),
    ("Islamic traditions frequently praise kindness and cleanliness toward cats.", "The household animal received a strong cultural endorsement."),
    ("Muezza is named in a popular modern legend as Muhammad’s beloved cat.", "The story is cherished, though early sources do not securely document it."),
    ("Trim sailed with explorer Matthew Flinders and was memorialized in Flinders’s writing.", "One ship’s cat earned a full literary performance review."),
    ("Mrs Chippy, despite the name, was a male cat on Shackleton’s Endurance expedition.", "Polar history preserved both the cat and the clerical error."),
    ("Simon of HMS Amethyst received the Dickin Medal after the Yangtze Incident.", "A ship’s cat became a decorated veteran and remained unimpressed."),
    ("‘Unsinkable Sam’ is a famous wartime ship-cat story with disputed documentation.", "Excellent lore; unreliable personnel file."),
    ("Pooli, a United States Navy ship’s cat, was photographed in a tiny uniform on her birthday.", "The uniform included ribbons. Discipline remained theoretical."),
    ("Polydactyl cats became strongly associated with ships and port communities.", "Extra toes acquired a maritime résumé."),
    ("Félicette became the first and only cat known to survive a trip to space.", "France launched one very unwilling astronaut in 1963."),
    ("Larry holds the official title Chief Mouser to the Cabinet Office in Britain.", "Government continuity now includes scheduled naps."),
    ("Palmerston served as Chief Mouser at Britain’s Foreign Office.", "Diplomacy gained a tuxedo department."),
    ("Cats have lived at St Petersburg’s Hermitage Museum as resident mousers for generations.", "Masterpieces receive basement security with whiskers."),
    ("Stubbs was celebrated for years as the honorary feline mayor of Talkeetna, Alaska.", "The title was unofficial; the constituent affection was not."),
    ("Towser worked as a mouser at Scotland’s Glenturret distillery.", "The whisky operation included a highly experienced pest consultant."),
    ("Dewey Readmore Books became the resident cat of the public library in Spencer, Iowa.", "He was returned through the book drop by fate."),
    ("Room 8 was a cat who repeatedly attended an elementary school in California.", "Enrollment paperwork never caught up with attendance."),
    ("Hodge, Samuel Johnson’s cat, is memorialized by a bronze statue in London.", "The dictionary household kept one excellent critic."),
    ("Socks lived in the White House during Bill Clinton’s presidency.", "The press office occasionally had a tail."),
    ("Orangey became a prolific animal actor and appeared in multiple films and television productions.", "One orange professional allegedly required several stand-ins."),
    ("Théophile Steinlen’s Le Chat Noir poster made a black cat an enduring image of Paris nightlife.", "The stare has outlived the cabaret."),
    ("Artist Louis Wain became famous for drawings of increasingly humanlike cats.", "Victorian cats obtained clothes, jobs, and social problems."),
    ("Edgar Allan Poe’s ‘The Black Cat’ turned feline unease into Gothic literature.", "The title cat received no relaxing scenes."),
    ("Lewis Carroll’s Cheshire Cat leaves its grin behind in Alice’s Adventures in Wonderland.", "The cat exits; customer service remains smiling."),
    ("T. S. Eliot’s Old Possum poems supplied cats with elaborate secret names and occupations.", "The private bureaucracy finally reached print."),
    ("Ernest Hemingway’s Key West home became associated with a colony of polydactyl cats.", "Literary tourism now includes bonus beans."),
    ("The tailless Manx cat is named for the Isle of Man.", "Island identity selected a very visible missing feature."),
    ("One Manx legend says Noah shut the Ark door on the last-arriving cat’s tail.", "The origin story blames a historic boarding delay."),
    ("Thai manuscripts called Tamra Maew describe auspicious and inauspicious cat types.", "Historic cat classification arrived with poetry and omens."),
    ("Birman breed lore tells of temple cats transformed by a goddess after a priest’s death.", "The sacred color change remains legend, not breeding records."),
]


RUMORS = [
    ("They say a black cat crossing your path brings bad luck.", "A widespread superstition, not feline traffic science."),
    ("They say a black cat brings good luck in parts of Britain.", "Same cat, opposite forecast. Folklore contains multitudes."),
    ("They say a strange black cat arriving at a Scottish home predicts prosperity.", "An old luck tradition, not financial advice."),
    ("They say a black cat near a bride promises a fortunate marriage.", "Wedding folklore gave the cat an unofficial planning role."),
    ("They say a cat sneezing near a bride foretells a happy marriage.", "A Japanese wedding superstition, not a compatibility test."),
    ("They say sailors considered a ship’s cat a sign of good luck.", "Maritime folklore grew around very practical mousers."),
    ("They say a sailor’s family kept a black cat to protect him at sea.", "British maritime superstition outsourced navigation to the household cat."),
    ("They say a ship’s cat washing behind its ears predicts rain.", "Weather lore noticed grooming and wrote a forecast."),
    ("They say a restless ship’s cat warns that a storm is coming.", "Sailor folklore, not a replacement for instruments."),
    ("They say throwing a ship’s cat overboard invites a terrible storm.", "Old sailors treated feline disrespect as meteorological sabotage."),
    ("They say a cat washing its face means visitors are coming.", "This guest forecast appears in several traditions."),
    ("They say the direction a cat faces while washing predicts where visitors come from.", "The grooming compass remains uncalibrated."),
    ("They say a cat washing both ears announces especially important company.", "Folklore upgraded the guest list based on grooming coverage."),
    ("They say a cat sleeping with paws over its nose predicts cold weather.", "A cozy observation became an old weather report."),
    ("They say a cat turning its back to the fire predicts a storm.", "Hearthside weather lore, not peer review."),
    ("They say a cat licking its tail foretells rain.", "The forecast has a 100 percent chance of grooming."),
    ("They say a cat racing wildly through the house predicts wind.", "Zoomies acquired a meteorology department."),
    ("They say a cat refusing to travel warns of danger ahead.", "Journey folklore respected the passenger who would not board."),
    ("They say letting a cat enter a new home first keeps bad spirits away.", "A housewarming tradition with built-in inspection."),
    ("They say a cat chooses the safest place for a baby’s cradle.", "Old household lore assigned the cat to site planning."),
    ("They say cats can steal a sleeping baby’s breath.", "A harmful old tale; cats do not steal breath."),
    ("They say dreaming of a cat warns of deceit nearby.", "Dream books blamed the sleeping cat for waking suspicions."),
    ("They say dreaming of a white cat predicts difficult times.", "One old dream superstition; the cat submitted no paperwork."),
    ("They say dreaming of kittens predicts small troubles multiplying.", "Dream folklore turned a litter into administrative foreshadowing."),
    ("They say a cat appearing at a funeral signals the dead person’s restless spirit.", "Mourning folklore, not evidence about either cats or ghosts."),
    ("They say a cat jumping over a coffin could wake the dead.", "European funeral superstition gave cats unreasonable permissions."),
    ("They say a cat sitting on a grave marks a troubled soul.", "Graveyard folklore, not a reliable spiritual audit."),
    ("They say witches can travel disguised as black cats.", "Early modern folklore caused real cats and people terrible harm."),
    ("They say a cat may serve as a witch’s familiar spirit.", "A European folklore role, not the cat’s actual employment."),
    ("They say a French matagot rewards a household that feeds it properly.", "A magical-black-cat legend with strict hospitality terms."),
    ("They say the Cat Sìth blesses homes that leave milk on Samhain.", "Scottish folklore recommends paying the fairy cat promptly."),
    ("They say the Cat Sìth curses homes that forget its Samhain saucer.", "The same folklore also invented supernatural late fees."),
    ("They say Japan’s raised-paw cat beckons luck through the door.", "Maneki-neko tradition, not a measurable force field."),
    ("They say a black cat can help a single woman attract suitors in Japan.", "A modern luck belief; results remain cat-dependent."),
    ("They say tortoiseshell cats protect Japanese sailors from storms and ghosts.", "Maritime folklore gave one coat pattern two security jobs."),
    ("They say an old Japanese cat may become a shape-shifting bakeneko.", "Yōkai folklore recommends monitoring senior-management permissions."),
    ("They say a long-lived cat may grow a forked tail and become a nekomata.", "A Japanese supernatural tale, not a veterinary prognosis."),
    ("They say the rat tricked the cat out of the Chinese zodiac race.", "A popular zodiac folktale explains a very old grudge."),
    ("They say Vietnam gave the Cat the Rabbit’s place in the zodiac.", "The Cat is genuinely in Vietnam’s zodiac; the reason lives in folklore."),
    ("They say a cat entering a Russian home first finds the safest sleeping place.", "Housewarming lore lets the cat conduct the first inspection."),
    ("They say the first night in a new Russian home should belong to the cat.", "Traditional house lore promoted one extremely confident tenant."),
    ("They say feeding the cat well before a Norwegian wedding brings sunshine.", "Wedding-weather folklore accepts payment in dinner."),
    ("They say an Italian cat sneeze brings good luck to whoever hears it.", "A cheerful superstition with no allergy data."),
    ("They say a cat sneezing three times predicts someone will catch a cold.", "Old household lore confused coincidence with diagnosis."),
    ("They say a black cat walking toward you brings luck, but walking away takes it.", "Direction-based folklore made the cat responsible for traffic flow."),
    ("They say finding a white hair on a black cat brings luck.", "A superstition that begins with an unauthorized coat inspection."),
    ("They say harming a cat brings years of misfortune.", "Many cultures use bad-luck stories to enforce the excellent rule: do not harm cats."),
    ("They say cats can sense ghosts staring from empty corners.", "The cat may hear a pipe. Folklore prefers a haunting."),
    ("They say a cat staring at the door sees a visitor before anyone else.", "Excellent hearing became supernatural reception duty."),
    ("They say cats have seven lives in some countries and nine in others.", "Folklore cannot settle the account; biology provides one."),
]


MEMES = [
    ("Loaf mode hides all four legs and most outstanding warrants.", "Geometry has withdrawn from the case."),
    ("A perfect loaf has no visible means of transportation.", "It still reaches the kitchen somehow."),
    ("The loaf is fully baked when the paws disappear.", "Do not insert a thermometer."),
    ("Somewhere inside this loaf, a cat is ignoring you.", "The location remains classified."),
    ("Loaf reaches final form: rectangle with opinions.", "Corners sold separately."),
    ("This loaf contains one cat and several complaints.", "Ingredients listed by volume."),
    ("The loaf has achieved structural purrfection.", "Building inspectors are baffled."),
    ("Emergency loaf deployed. Situation unchanged.", "Excellent posture; no measurable assistance."),
    ("Compact loaf saves space for additional crimes.", "Storage optimization is complete."),
    ("The loaf refuses all questions about its missing legs.", "Legal counsel is present."),
    ("A blep is one tongue pixel left on-screen.", "Refresh unavailable."),
    ("Blep detected. Seriousness levels approaching zero.", "The face has lost containment."),
    ("One tiny blep can cancel an entire villain monologue.", "Dignity disconnected."),
    ("The tongue has left the office without logging out.", "Classic blep procedure."),
    ("Blep remains deployed after all systems shut down.", "No technician has claimed responsibility."),
    ("A mlem is a lick with excellent public relations.", "Same tongue, stronger branding."),
    ("Mlem protocol begins when dinner looks inspectable.", "Quality assurance has arrived."),
    ("The mlem is brief. The screenshot is forever.", "Internet preservation succeeds again."),
    ("Blep is idle tongue. Mlem is active tongue.", "The internet has standards, somehow."),
    ("Tongue out, thoughts unavailable.", "Please try the braincell later."),
    ("Toe beans are the official currency of looking adorable.", "Exchange rate remains extremely favorable."),
    ("These beans are not for eating or touching without permission.", "The farmer has claws."),
    ("Fresh toe beans installed on every corner.", "Traction package included."),
    ("The beans have voted against standing up.", "Motion defeated unanimously."),
    ("One paw contains beans, knives, and no remorse.", "A complete field kit."),
    ("Toe bean inspection has been denied.", "Submit form PS-PS-PS tomorrow."),
    ("The paw appears soft because the weapons are concealed.", "Excellent industrial design."),
    ("Bean arrangement remains proprietary.", "Competitors keep asking."),
    ("Tiny socks are painted directly onto management.", "Laundry requirements reduced."),
    ("The murder mittens are currently in cuddle configuration.", "Firmware may change without warning."),
    ("If I fits, I sits. Appeals are not accepted.", "Container law predates human law."),
    ("The box is two sizes too small, therefore perfect.", "Cat geometry has spoken."),
    ("Every empty box is pre-approved cat housing.", "Zoning cannot stop this."),
    ("Box ownership transfers at first contact.", "No signature required."),
    ("The cat fits because reality moved slightly.", "Physics agreed under pressure."),
    ("Cardboard castle acquired. Mortgage: zero.", "The housing market fears this cat."),
    ("This box contains more cat than volume allows.", "Please ignore the measurements."),
    ("Shipping label says fragile. Cat says occupied.", "Delivery rescheduled indefinitely."),
    ("Sink goblin has claimed the porcelain district.", "Water service remains uncertain."),
    ("You dare enter the goblin’s sink.", "Bathroom access revoked."),
    ("The laptop is warm, expensive, and therefore a bed.", "Your deadline is not relevant."),
    ("Keyboard cat has submitted seventeen blank documents.", "Productivity metrics are excellent."),
    ("The cat sits precisely on the keys you need.", "Targeting systems operational."),
    ("Laptop closed by authorized furry personnel.", "Work-life balance enforced."),
    ("The cursor moved, so the hunt begins.", "Spreadsheet casualties expected."),
    ("Your keyboard now types exclusively in cat.", "Language pack installed."),
    ("The webcam angle has become deeply unflattering.", "Meeting attendance increased."),
    ("Cat on keyboard. Password security compromised by beans.", "Access granted accidentally."),
    ("The charger belongs to the cat now.", "Battery negotiations have failed."),
    ("Remote work means working around the cat.", "The contract was very clear."),
    ("Zoomies begin when the hallway least expects them.", "Traffic control has resigned."),
    ("Midnight zoomies have entered the second floor.", "Sleep has been evacuated."),
    ("The braincell connected. Maximum speed followed.", "No steering update was included."),
    ("One braincell, currently buffering.", "Estimated completion: never."),
    ("The orange cat awaits its turn with the braincell.", "Queue position unknown."),
    ("Braincell acquired briefly, used for crime.", "Resource allocation questioned."),
    ("Zoomie trajectory approved by nobody.", "Walls are merely suggestions."),
    ("Sudden acceleration. No mission statement.", "The hallway accepts its fate."),
    ("The cat has entered airplane mode.", "Ears flattened; service unavailable."),
    ("Airplane ears indicate immediate departure from nonsense.", "Flight delayed by snacks."),
    ("Longcat is long. Scholarship concluded.", "Further research would be redundant."),
    ("Ceiling Cat has reviewed the incident.", "The report is mostly judgment."),
    ("Basement Cat requests one tiny favor.", "Do not sign anything."),
    ("Keyboard Cat plays us off another bad decision.", "The credits begin early."),
    ("Nyan Cat continues through space on obsolete bandwidth.", "The rainbow has excellent uptime."),
    ("Grumpy Cat established the permanent complaint department.", "Office hours: all of them."),
    ("Schrödinger’s box contains one cat and endless discourse.", "Do not open the comment section."),
    ("The internet saw a cat and invented a language.", "Blep was inevitable."),
    ("Ancient forum prophecy: pics or it didn’t happen.", "The cat picture survives."),
    ("This cat has seen the loading screen.", "Progress remains at three percent."),
    ("Majestic idiot surveys the kingdom.", "The kingdom is one laundry basket."),
    ("Tiny criminal returns to the scene.", "Evidence is stuck to one whisker."),
    ("Cat.exe has stopped responding to authority.", "This is expected behavior."),
    ("Error 404: dignity not found.", "Cat located successfully."),
    ("Please wait. Cat is installing chaos.", "Restarting will not help."),
    ("The feline firewall blocks all productivity.", "Treat packets may pass."),
    ("System update adds one unnecessary scream.", "Patch cannot be rolled back."),
    ("Single braincell is already in another tab.", "Memory pressure critical."),
    ("Cat has administrator privileges for unknown reasons.", "Your account is now decorative."),
    ("Household management has rejected your seating request.", "The chair remains occupied."),
    ("Management requests dinner despite recent dinner.", "Previous payment was apparently unrelated."),
    ("The cat is not yelling. It is filing verbally.", "Complaint volume set to maximum."),
    ("Your performance review mentions insufficient lap availability.", "Improvement plan begins immediately."),
    ("The supervisor sleeps through every important meeting.", "Leadership style: horizontal."),
    ("Human resources has been replaced by feline resources.", "Benefits now include fur."),
    ("The cat owns the home; humans handle maintenance.", "A standard landlord arrangement."),
    ("Dinner was seven minutes late. Trust is rebuilding.", "Full recovery may require chicken."),
    ("Personal space is a rule for other people.", "Cat access remains unrestricted."),
    ("The household follows one schedule: cat o’clock.", "All alarms are biological."),
    ("Majestic energy, deeply questionable plan.", "Confidence exceeds available information."),
    ("This angle was approved by an enemy.", "Chin department fully exposed."),
    ("Glass has interrupted the face unexpectedly.", "Smush protocol complete."),
    ("The yawn contains a small portal.", "Do not approach the event horizon."),
    ("Mid-sneeze cat briefly leaves this dimension.", "Return expected after one frame."),
    ("The jump looked better before the screenshot.", "History remembers the landing setup."),
    ("Caught mid-fall, still blaming gravity.", "Legal action remains pending."),
    ("The fisheye lens has committed a personal offense.", "Belly dimensions under appeal."),
    ("One fang remains outside for ventilation.", "Building code allows it."),
    ("Blep plus crossed eyes equals full bandwidth.", "No additional thoughts can enter."),
    ("The cat is screaming in lowercase.", "Volume somehow remains uppercase."),
]
